---
title: "INFO523 - Decision Trees"
author: "Sebastian Deimen & Noah Giebink"
date: "21 März 2020"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)


# packages

# install.packages("xfun")
#library(xfun)

libs <- c("rpart","rpart.plot","tidyverse", "adabag",  "rsample","ipred","randomForest","gbm","DMwR2")
xfun::pkg_attach(libs)

spot <- read.csv("spot_clean.csv")

set.seed(28)
```



```{r}
# preprocessing the data set 


spot_music <- spot %>% select(track.popularity, track.explicit, danceability, key, loudness, mode, 
                        speechiness, acousticness, instrumentalness,
                        liveness, valence, tempo, country)

# trying another set of varibales due to horrible error rates for the first set
# I tried without track.popuarity, makes it worse, so another try, including socio-variables

spot_music_socio <- spot %>% select(track.popularity, track.explicit, danceability, key, loudness, mode, 
                        speechiness, acousticness, instrumentalness,
                        liveness, valence, tempo, happiness, median_age, percent_urban, 
                        percent_internet_users, density_sqkm, freedom, gdp, country)
```

The spot_music splitting: 

```{r}

# splitting the data, two differnet ways: one with CreateDataPartition, second with sample

# first: 


split_index <- createDataPartition(spot_music$country, p= 0.8, list = F)

spot_music_train <- spot_music[split_index,]
spot_music_features_test <- spot_music[-split_index, !(colnames(spot_music) %in% c("country"))]
spot_music_target_test <- spot_music[-split_index, "country"]
 
# second:   
  

index <- sample(1:nrow(spot_music),929)
train <- spot_music[index,]
test <- spot_music[-index,]

```


The spot_music trees and error rates:


```{r}
# making two trees from different trainings sets


ct_create <- rpartXse(country ~ ., spot_music_train, se=0.5)
ct_sample <- rpartXse(country ~ ., train, se=0.5)

# prediction using the trees


ps_create <- predict(ct_create, spot_music_features_test, type = "class")

ps_sampel <- predict(ct_sample, test, type = "class")

# have a look at the variable.importance
ct_create$variable.importance
ct_sample$variable.importance

# contingency tables

cm_create <- table(ps_create, spot_music_target_test)
cm_sample <- table(ps_sampel,test$country)

# error rate
error_create <- (1-sum(diag(cm_create))/sum(cm_create))
cat("error_create rate:",error_create)
                    
error_sample <- (1-sum(diag(cm_sample))/sum(cm_sample))

cat("error_sample rate:",error_sample)
```


The spot_music_SOCIO splitting: 

```{r}
# splitting the data, two differnet ways: one with CreateDataPartition, second with sample

# first: 

split_index <- createDataPartition(spot_music_socio$country, p= 0.8, list = F)

spot_music_socio_train <- spot_music_socio[split_index,]
spot_music_socio_features_test <- spot_music_socio[-split_index, !(colnames(spot_music_socio) %in% c("country"))]
spot_music_socio_target_test <- spot_music_socio[-split_index, "country"]
  
  
# second:   
  
index <- sample(1:nrow(spot_music_socio),929)
train <- spot_music_socio[index,]
test <- spot_music_socio[-index,]


```

The spot_music_socio_SOCIO trees:

```{r}
# making two trees from different trainings sets

ct_create <- rpartXse(country ~ ., spot_music_socio_train, se=0.5)
ct_sample <- rpartXse(country ~ ., train, se=0.5)

# prediction using the trees

ps_create <- predict(ct_create, spot_music_socio_features_test, type = "class")
ps_sampel <- predict(ct_sample, test, type = "class")

# have a look at the variable.importance
ct_create$variable.importance
ct_sample$variable.importance

# contingency tables
cm_create <- table(ps_create, spot_music_socio_target_test)
cm_sample <- table(ps_sampel,test$country)

# error rate
error_create <- (1-sum(diag(cm_create))/sum(cm_create))
cat("error_create rate:",error_create)
                    
error_sample <- (1-sum(diag(cm_sample))/sum(cm_sample))
cat("error_sample rate:",error_sample)



```








